language: rust
sudo: false
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
rust:
    - stable
    - beta
    - nightly
install:
    - pip install --user codecov
    - export PATH=$HOME/.local/bin:HOME/local/bin:$PATH
script:
    - cargo build
    - cargo test
    - cargo test --release
    - |
      if test "${TRAVIS_RUST_VERSION}" == "nightly"; then
          cargo test --features unstable
      fi
after_success:
    # Build and cache kcov
    - |
      if [ -f $HOME/local/bin/kcov ]; then
          echo "Using cached kcov from ~/local/bin/kcov"
      else
          mkdip -p $HOME/local
          cd $HOME/local
          wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz
          tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build
          cmake -DCMAKE_INSTALL_PREFIX=$HOME/local ..
          make install
          cd $TRAVIS_BUILD_DIR
      fi
    - |
      if test "${TRAVIS_RUST_VERSION}" == "stable"; then
          export PATH=$HOME/local/bin:$PATH
          kcov --include-pattern=$(pwd) target/kcov target/debug/mudi-*
          codecov --file target/kcov/mudi-*/cobertura.xml
      fi
cache:
  directories:
      - $HOME/local
