language: rust
sudo: false
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
rust:
    - stable
    - beta
    - nightly
install:
    - pip install --user codecov travis-cargo
    - export PATH=$HOME/.local/bin:HOME/local/bin:$PATH
script:
    - cargo build
    - cargo test
    - cargo test --release
    - |
      if test "${TRAVIS_RUST_VERSION}" == "nightly"; then
          cargo test --features unstable
      fi
after_success:
    # Build and cache kcov
    - |
      if [ -f $HOME/local/bin/kcov ]; then
          echo "Using cached kcov from ~/local/bin/kcov"
      else
          mkdip -p $HOME/local
          cd $HOME/local
          wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz
          tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build
          cmake -DCMAKE_INSTALL_PREFIX=$HOME/local ..
          make install
          cd $TRAVIS_BUILD_DIR
      fi
    - |
      if test "${TRAVIS_RUST_VERSION}" == "stable"; then
          export PATH=$HOME/local/bin:$PATH
          kcov --include-pattern=$(pwd) target/kcov target/debug/mudi-*
          codecov --file target/kcov/mudi-*/cobertura.xml
      fi
    - travis-cargo --only stable doc
    - travis-cargo --only stable doc-upload
cache:
  directories:
      - $HOME/local
env:
  global:
    secure: kHOi2qxVEdvXuPsGgH5r3UURoWIvV037zfpwp4IVQiRSk4uFMmt65kDDgpqQB/HA0Vw3Itf7RBKj/eBqUX1sDBnfn1/Lk2P/VGCHm1rrbrjrnMqm8GtwnHLJfFkzxO8ewej50bEYLgob725z6YRq1F9twsm+HAyazk270SbHBKu8s+Qmkuf0S77Lr62frB9JRaIq63SGFpEoM/Bk1kn0dxJx5NYY4EzvoYVzcPA9uWxpSnvEzmHdDqkW4C1sF2bb0JuBprvY64QR0YTmSykp7ClSdeqdBKbNJ+cnoVlndkh/R34KairQFEbypvFgWS8sQbf4vBQifndHAX4RiXvYHcgm9nQnoTY+AKtBo67rjP+v2O6i/ZvzauE2GPoFuh2L+ZAcUeaGYieOCVEcG9eVPfSWez7TFHPBD3/q0tpdaZA9LY3lRiUG75jTDelPwQAsGur1EkgL8aejqp0ZTmI0NgfYauCvrnTMSy4hCN+pFfQMnoYNj/93vXHMYxHjelWoDOvsN0wunXaMTRQi9hXZJZuDoJ6XYpd2bD8F9Muwe6TMPV0Jj4Iq703pZzatumwO3v3aRiPeKp0X+ieYQ0w0PF4MaULIXpbQAbRtdL/T4qxMCt7/5VIqGbTvztqidepQLhBnF083lyqx1rhyDx9voNVV8FA7vDlRfPE0A+TuHTs=
